### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.util.Set.add(Object)" because the return value of "java.util.Deque.peekLast()" is null

### ISSUE THREAD

**Issue by fab-10** [Consensys/linea-arithmetization#658]
When restarting the sequencer, during the first block production this exception is thrown:

```
2024-03-29 14:04:36.810+00:00 | EthScheduler-BlockCreation-0 | ERROR | MainnetTransactionProcessor | Critical Exception Processing Transaction
java.lang.NullPointerException: Cannot invoke "java.util.Set.add(Object)" because the return value of "java.util.Deque.peekLast()" is null
        at net.consensys.linea.zktracer.container.stacked.set.StackedSet.add(StackedSet.java:124) ~[?:?]
        at net.consensys.linea.zktracer.module.modexpdata.ModexpData.call(ModexpData.java:54) ~[?:?]                                                                                                                              at net.consensys.linea.zktracer.module.limits.precompiles.ModexpEffectiveCall.tracePreOpcode(ModexpEffectiveCall.java:149) ~[?:?]                                                                                         at net.consensys.linea.zktracer.module.hub.Hub.triggerModules(Hub.java:479) ~[?:?]                                                                                                                                        at net.consensys.linea.zktracer.module.hub.Hub.processStateExec(Hub.java:541) ~[?:?]                                                                                                                                      at net.consensys.linea.zktracer.module.hub.Hub.tracePreOpcode(Hub.java:818) ~[?:?]                                                                                                                                        at net.consensys.linea.zktracer.ZkTracer.tracePreExecution(ZkTracer.java:189) ~[?:?]                                                                                                                                      at org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:199) ~[besu-evm-24.3-develop-269710e041.jar:24.3-develop-269710e041]                                                                                                   at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:174) ~[besu-evm-24.3-develop-269710e041.jar:24.3-develop-269710e041]                                             at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:200) ~[besu-evm-24.3-develop-269710e041.jar:24.3-develop-269710e041]                                                 at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:540) ~[besu-core-24.3-develop-269710e041.jar:24.3-develop-269710e041]                                       at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:425) ~[besu-core-24.3-develop-269710e041.jar:24.3-develop-269710e041]                            at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:245) ~[besu-core-24.3-develop-269710e041.jar:24.3-develop-269710e041]                            at org.hyperledger.besu.ethereum.blockcreation.txselection.BlockTransactionSelector.processTransaction(BlockTransactionSelector.java:328) ~[besu-blockcreation-24.3-develop-269710e041.jar:24.3-develop-269710e041]                                                                                                     
```

**Comment by letypequividelespoubelles** [comment]
@powerslider can you check if it's ok in the branch `feat/issue-142/mmio` ? I think I already fixed there. The precompileLimit module were creating a new instance of `BlakeModexp` module instead of taking the one from the `hub`. I think that fixes the issue.

**Comment by letypequividelespoubelles** [comment]
it's fixed on the mmio branch. You forget to add the blakemodexpmodule in the `modules` of the hub too
